"""
Mock hackathon data for testing hackfind without network access.
Run: python main.py --mock --tags ai
"""

MOCK_HACKATHONS = [
    {
        "title": "AI for Good Hackathon 2025",
        "url": "https://devpost.com/hackathons/ai-for-good-2025",
        "date": "2025-04-15 → 2025-04-17",
        "prize": "$10,000",
        "tags": ["ai", "machine learning", "social impact"],
        "location": "Online",
        "source": "Devpost",
    },
    {
        "title": "ETHGlobal Bangkok",
        "url": "https://ethglobal.com/events/bangkok",
        "date": "2025-05-01 → 2025-05-03",
        "prize": "$50,000",
        "tags": ["blockchain", "web3", "ethereum", "defi"],
        "location": "Bangkok, Thailand",
        "source": "Devpost",
    },
    {
        "title": "HackMIT 2025",
        "url": "https://hackmit.org",
        "date": "2025-09-13 → 2025-09-14",
        "prize": "$5,000",
        "tags": ["open source", "hardware", "web"],
        "location": "Cambridge, MA",
        "source": "MLH",
    },
    {
        "title": "Climate Tech Hackathon",
        "url": "https://devfolio.co/hackathons/climate-tech",
        "date": "2025-04-20 → 2025-04-22",
        "prize": "$8,000",
        "tags": ["climate", "sustainability", "iot", "ai"],
        "location": "Online",
        "source": "Devfolio",
    },
    {
        "title": "HealthHack 2025",
        "url": "https://hackathon.com/events/healthhack",
        "date": "2025-05-10 → 2025-05-12",
        "prize": "$15,000",
        "tags": ["health", "biotech", "ai", "mobile"],
        "location": "London, UK",
        "source": "Hackathon.com",
    },
    {
        "title": "Web3 Gaming Summit Hack",
        "url": "https://devpost.com/hackathons/web3-gaming",
        "date": "2025-06-01 → 2025-06-03",
        "prize": "$25,000",
        "tags": ["game", "blockchain", "nft", "web3"],
        "location": "Online",
        "source": "Devpost",
    },
    {
        "title": "Open Source AI Sprint",
        "url": "https://devfolio.co/hackathons/oss-ai",
        "date": "2025-04-28 → 2025-04-29",
        "prize": "",
        "tags": ["ai", "open source", "python", "llm"],
        "location": "Online",
        "source": "Devfolio",
    },
    {
        "title": "FinTech Disrupt Hackathon",
        "url": "https://hackathon.com/events/fintech-disrupt",
        "date": "2025-05-15 → 2025-05-17",
        "prize": "$20,000",
        "tags": ["fintech", "payments", "blockchain"],
        "location": "New York, NY",
        "source": "Hackathon.com",
    },
    {
        "title": "MLH Local Hack Day: Build",
        "url": "https://mlh.io/seasons/2025/events",
        "date": "2025-04-12",
        "prize": "",
        "tags": ["hack", "open source"],
        "location": "Online",
        "source": "MLH",
    },
    {
        "title": "Security & Privacy Hackathon",
        "url": "https://devpost.com/hackathons/security-2025",
        "date": "2025-07-04 → 2025-07-06",
        "prize": "$12,000",
        "tags": ["security", "privacy", "cryptography"],
        "location": "Online",
        "source": "Devpost",
    },
]
